version: '3'

services:
  audio-api:
    build: .
    ports:
      - "${EXTERNAL_PORT:-8000}:8000"
    volumes:
      - ./logs:/app/logs
      - ./downloads_temp:/app/downloads_temp
    env_file:
      - .env
    restart: unless-stopped 