version: '3'

services:
  audio-processor:
    build: .
    container_name: audio-processor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./downloads_temp:/app/downloads_temp
    environment:
      - TZ=Asia/Shanghai 